FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    make \
    gcc-mingw-w64-x86-64 \
    libz-mingw-w64-dev \
    patch \
    zip \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /lupinho
COPY . /lupinho/
RUN patch -d /lupinho/src/libs/lua -p1 /lupinho/src/libs/lua-5.5.1-binary-literals.patch
# Install Lua 5.5.1
RUN cd /lupinho/src/libs/lua && make CC=x86_64-w64-mingw32-gcc
ENV PATH=$PATH:/lupinho/src/libs/lua
RUN make -C /lupinho/src windows
